# Generated by Django 3.1.7 on 2021-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('job_details', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(blank=True)),
                ('job_link', models.TextField(blank=True)),
            ],
        ),
    ]
